Repository SOPT-all/36-SOPKATHON-ANDROID-ANDROID2, pull requests merged in 2025-05, with the labels that each got.

#5 [MOD] Change README.md
  README.md
Labels: MOD ✅, 종명

#7 [MOD] Update README.md
  README.md
Labels: MOD ✅, 종명

#14 [FEAT/#11] BaseResponse 구현
  app/src/main/java/org/sopt/sopkathon/data/dummy/dto/response/BaseResponse.kt
Labels: SETTING ⚙️, FEAT :sparkles:, 민성

#15 [FEAT/#13] 네트워크 관련 설정
  app/src/main/java/org/sopt/sopkathon/data/.gitkeep
  app/src/main/java/org/sopt/sopkathon/data/remote/NetworkModule.kt
  app/src/main/java/org/sopt/sopkathon/data/remote/RetrofitExtension.kt
  app/src/main/java/org/sopt/sopkathon/data/remote/qualifier/NetworkQualifier.kt
Labels: FEAT :sparkles:, 종명

#4 [SETTING/#3] color font setting
  app/src/main/java/org/sopt/sopkathon/core/designsystem/theme/Color.kt
  app/src/main/java/org/sopt/sopkathon/core/designsystem/theme/Type.kt
  app/src/main/res/font/pretendard_medium.otf
  app/src/main/res/font/pretendard_regular.otf
  app/src/main/res/font/pretendard_semibold.otf
Labels: SETTING ⚙️, 혜정

#18 [FEAT#16] 화면 네비게이션 구현
  app/src/main/java/org/sopt/sopkathon/presentation/detail/DetailScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/detail/navigation/DetailNavigation.kt
  app/src/main/java/org/sopt/sopkathon/presentation/dummy/component/.gitkeep
  app/src/main/java/org/sopt/sopkathon/presentation/dummy/navigation/DummyNavigation.kt
  app/src/main/java/org/sopt/sopkathon/presentation/guide/GuideScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/guide/navigation/GuideNavigation.kt
  app/src/main/java/org/sopt/sopkathon/presentation/main/MainActivity.kt
  app/src/main/java/org/sopt/sopkathon/presentation/main/MainNavigator.kt
  app/src/main/java/org/sopt/sopkathon/presentation/main/MainScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/main/MainTab.kt
  app/src/main/java/org/sopt/sopkathon/presentation/map/MapScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/map/navigation/MapNavigation.kt
  app/src/main/java/org/sopt/sopkathon/presentation/purchase/PurchaseScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/purchase/navigation/PurchaseNavigation.kt
  app/src/main/java/org/sopt/sopkathon/presentation/splash/SplashScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/splash/navigation/SplashNavigation.kt
Labels: FEAT :sparkles:, 종명

#21 [FEAT#20] 맵 뷰 구현
  app/src/main/java/org/sopt/sopkathon/presentation/map/MapScreen.kt
  app/src/main/java/org/sopt/sopkathon/presentation/map/RegionType.kt
  app/src/main/java/org/sopt/sopkathon/presentation/map/component/ClickableMap.kt
  app/src/main/java/org/sopt/sopkathon/presentation/map/component/MapGoStoreButton.kt
  app/src/main/java/org/sopt/sopkathon/presentation/map/navigation/MapNavigation.kt
Labels: UI :iphone:, FEAT :sparkles:, 민성

#22 [Feat/#19] 공통 컴포넌트 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/sopt/sopkathon/core/designsystem/component/.gitkeep
  app/src/main/java/org/sopt/sopkathon/core/designsystem/component/MapSelectButton.kt
  app/src/main/java/org/sopt/sopkathon/core/designsystem/component/PurchaseItem.kt
  app/src/main/java/org/sopt/sopkathon/core/designsystem/component/TopBar.kt
  app/src/main/res/drawable/ic_arrow.xml
  app/src/main/res/drawable/ic_arrow_left_black.xml
  app/src/main/res/drawable/ic_review_black.xml
  app/src/main/res/drawable/img_map.xml
  app/src/main/res/values/strings.xml
Labels: FEAT :sparkles:, 혜정
